declare module "virtual:zomoc" {
  import type { UrlRegistry, TypeRegistry } from "./types"

  /**
   * A map of URL patterns to their corresponding Zod schemas and configurations, generated by Zomoc.
   */
  export const finalSchemaUrlMap: UrlRegistry
  /**
   * A map of type names to their corresponding Zod schemas, generated by Zomoc.
   */
  export const finalSchemaTypeMap: TypeRegistry
}
