declare module "virtual:zomoc" {
  import type { ZodTypeAny } from "zod"

  export interface RegistryValue {
    schema: ZodTypeAny
    pagination?: {
      itemsKey: string
      totalKey: string
      pageKey: string
      sizeKey: string
    }
    strategy?: "random" | "fixed"
    repeatCount?: number
  }

  /**
   * A map of URL patterns to their corresponding Zod schemas and configurations, generated by Zomoc.
   */
  export const finalSchemaUrlMap: Record<string, RegistryValue>
}
