declare module "virtual:zomoc" {
  import type { ZodTypeAny } from "zod"

  /**
   * A map of URL patterns to their corresponding Zod schemas, generated by Zomoc.
   */
  export const finalSchemaUrlMap: Record<string, ZodTypeAny>
}
